[package]
name = "fork"
version = "0.1.0"
edition = "2021"

[lib]
name = "blockchain"
path = "blockchain/src/blockchain.rs"


[dependencies]
num-bigint = { version = "0.4", features = ["rand"] }
sha2="0.9.0"
rand="0.8.0"
borsh = "0.9.1"